# Generated by Django 3.2.21 on 2023-11-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_alter_workshops_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('workshop_enquiry', models.TextField(default='', max_length=600)),
            ],
        ),
    ]
