# Generated by Django 3.2.21 on 2023-11-11 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_workshopcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopcontact',
            name='workshop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshops.workshops'),
        ),
    ]
