# Generated by Django 3.2.21 on 2023-11-12 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0004_workshopcontact_workshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopcontact',
            name='workshop',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshops.workshops'),
        ),
    ]
