# Generated by Django 3.2.21 on 2023-10-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
